const express = require('express');
const router = express.Router();
const { submitFeedback, getAllFeedback, deleteFeedback, getFeedbackStats  } = require('../controllers/feedbackController');
const protect = require('../middleware/authMiddleware');
router.get('/', protect, getAllFeedback);
router.post('/submit', submitFeedback);
router.get('/', getAllFeedback);
router.delete('/:id', protect, deleteFeedback);
router.get('/stats', protect, getFeedbackStats);
module.exports = router;
